[package]
name = "fixx"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/NuschtOS/ixx/"

[lib]
crate-type = ["cdylib"]

[dependencies]
libixx = { path = "../libixx" }
wasm-bindgen = "0.2"
