[package]
name = "libixx"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/NuschtOS/ixx/"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
bincode = "1.3"

[dev-dependencies]
serde_json = "1.0"
